version: '3.5'

services:
  database:
    image: mysql
    container_name: store
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3307:3306

volumes:
  mysql_volume: