version: '3.5'

services:
  database:
    image: mysql
    container_name: final_project
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306